Update spacing voorbeeld spacing design tokens
frameless/nl-design-system-templates pull request #208
Opened 2023-10-10 15:46 UTC by MeesoPost

### Changes 

- added design tokens used for spacing from the [figma](https://www.figma.com/file/OlnanjplmeO3aWYzNKnNTo/Voorbeeld---Templates?node-id=510%3A2189&mode=dev) 
-  used :is to be more compact
- changed H4 to H2 because that is how it is in the [figma](https://www.figma.com/file/OlnanjplmeO3aWYzNKnNTo/Voorbeeld---Templates?node-id=510%3A2189&mode=dev)
- removed the paragraph surrounding the breadcrumbs because it is not allowed

2023-10-11 14:46 UTC, scar055 requested changes

2023-10-11 14:46 UTC, scar055 commented on packages/next-templates/src/app/globals.css
> -  /* HACK: these tokens are not set in utrecht-theme */
kijk of de tokens ook weg kunnen anders moet de comment weer terug

2023-10-11 14:46 UTC, scar055 commented on packages/next-templates/src/app/styling/css/detail-page.css
>  .utrecht-ordered-list__item {
dit niet in het utrecht class stoppen tenzij het overal moet verandert worden

2023-10-11 14:46 UTC, scar055 commented on packages/next-templates/src/app/styling/css/form-page.css
> +.voorbeeld-telefoon-textbox-small {
als het niet werkt kan het weg

2023-10-17 11:47 UTC, scar055 requested changes

2023-10-17 11:47 UTC, scar055 commented on packages/next-templates/src/app/styling/css/detail-page.css
> +.voorbeeld-breadcrumb-text-decoration-skip-ink {
de class kn je beter de skip ink weghalen voor betere benaming

2023-10-17 11:47 UTC, scar055 commented on packages/next-templates/src/app/page.tsx
> +            <BreadcrumbNavLink className="voorbeeld-breadcrumb-text-decoration-skip-ink" href="" index={0} rel="home">
class name beter naar voorbeeld-breadcrumb-text-decoration veranderen

2023-10-17 11:47 UTC, ryanvvalkenhoef approved these changes

2023-10-17 11:57 UTC, scar055 approved these changes

2023-10-17 11:59 UTC, ryanvvalkenhoef approved these changes

2023-10-17 12:14 UTC, merged