Ingelogd stap1
frameless/nl-design-system-templates pull request #264
Opened 2023-10-31 16:14 UTC by MeesoPost

2023-10-31 16:27 UTC, scar055 requested changes

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wmebv/ingelogd/stap1/page.tsx
> +      <ExampleHeaderWmebv></ExampleHeaderWmebv>
self closing tags

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wmebv/niet-ingelogd/stap1/page.tsx
> +            <UtrechtParagraph className="voorbeeld-paragraph-bijlage">Bijlage</UtrechtParagraph>
vind persoonlijk dat je niet 2 paragraphs gebruikt voor 1 zin dat je beter er in een span gebruikt maar je kan aan robbert vragen

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
> +            <UtrechtTextbox />
name toevoegen bij textboxes

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
> +            <UtrechtTextbox />
is bij elke textbox

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wrong-forms/maandagochtend/page.tsx
wilt mees niet toevoegen

2023-10-31 16:27 UTC, scar055 commented on packages/next-templates/src/app/wrong-forms/page.tsx
ook weg door mees gezegd

2023-10-31 16:29 UTC, scar055 commented on packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
> +            <UtrechtTextbox />
label ook nog toevoegen

2023-10-31 16:31 UTC, MeesoPost commented on packages/next-templates/src/app/wmebv/niet-ingelogd/stap2/page.tsx
> +            <UtrechtTextbox />
type

2023-11-03 11:12 UTC, AnoniemeBoebe approved these changes

2023-11-07 10:53 UTC, merged