Ryan demo
frameless/nl-design-system-templates pull request #56
Opened 2023-09-05 13:10 UTC by ryanvvalkenhoef

Can you review my PR?

2023-09-05 13:13 UTC, MeesoPost requested changes

2023-09-05 13:13 UTC, MeesoPost commented on packages/next-templates/src/app/ryan/form/page.tsx
> +        <br />
🤮

2023-09-06 12:39 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/ryan/form/page.tsx
> +        <br />
🖕

2023-09-06 12:54 UTC, scar055 commented on packages/next-templates/src/app/page.tsx
> +import Logo from './styling/assets/voorbeeld-footer.svg';
is de verkeerde svg want nu wordt hij toch wit

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
>            <br />
no

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
>              <br />
brrrrr

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
> +              <br />
brrrr

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
> +            <br />
brrrrr

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
> +              <br />
brrr

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
>              <br />
brrrr

2023-09-06 12:55 UTC, scar055 commented on packages/next-templates/src/app/ryan/form/page.tsx
>            <br />
brrrr

2023-09-06 12:57 UTC, scar055 commented on packages/next-templates/src/app/styling/component-styles/footer.css
> +  --utrecht-link-color: white !important;
important?

2023-09-06 12:59 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/ryan/form/page.tsx
>              <br />
🖕

2023-09-06 12:59 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/ryan/form/page.tsx
> +              <br />
🖕

2023-09-06 12:59 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/ryan/form/page.tsx
> +            <br />
🖕

2023-09-06 13:00 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/ryan/form/page.tsx
>            <br />
🖕

2023-09-06 13:00 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/styling/component-styles/footer.css
> +  --utrecht-link-color: white !important;
🖕

2023-09-06 13:00 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/styling/component-styles/footer.css
> +  --utrecht-link-color: white !important;
🖕

2023-09-06 13:21 UTC, scar055 approved these changes
als morgen niet de br weg zijn ga ik geen pr meer approven tot ze weg zijn

2023-09-06 13:24 UTC, MeesoPost approved these changes
br = vies 🤮

2023-09-06 13:24 UTC, MeesoPost approved these changes

2023-09-06 13:27 UTC, merged